name: Build & Release Executável

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Criar venv, instalar dependências e compilar
      shell: cmd
      run: |
        python -m venv venv
        call venv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pyinstaller --onefile ^
          --add-data "templates\\letra_sumario.json;templates" ^
          --add-data "bin\\7z.exe;bin" ^
          --add-data "venv\\Lib\\site-packages\\pyfiglet\\fonts;pyfiglet\\fonts" ^
          vidsender.py

    - name: Publicar executável na Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/vidsender.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}