name: Build & Release Executável

on:
  push:
    tags:
      - 'v*'  # ex: v1.0, v2.1.3, etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Criar ambiente virtual e instalar dependências
      run: |
        python -m venv venv
        .\venv\Scripts\activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Compilar com PyInstaller
      run: |
        .\venv\Scripts\activate
        pyinstaller --onefile ^
          --add-data "templates\\letra_sumario.json;templates" ^
          --add-data "bin\\7z.exe;bin" ^
          --add-data "venv\\Lib\\site-packages\\pyfiglet\\fonts;pyfiglet\\fonts" ^
          vidsender.py

    - name: Criar Release e fazer upload do executável
      uses: softprops/action-gh-release@v1
      with:
        files: dist/vidsender.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
